### PR TITLE
Add Zenaton in Pipeline frameworks & libraries Section

### PR DESCRIPTION
**Pull request by LouisGraffeuil**

### CODE REVIEW

**Comment by pditommaso** [comment]
Nice. thanks.

**Comment by LouisGraffeuil** [comment]
@pditommaso thanks for your reply. You just closed it instead of merging it. Let me know if something is missing ;)

**Comment by pditommaso** [comment]
Oops

**Comment by pditommaso** [comment]
ok, now merged 😄

**Pull request merged**
