### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by hanan-vian**

### CODE REVIEW

**Comment by pditommaso** [comment]
Thanks for this contrib. Please provide the GH repo instead of the link to the docs.

**Comment by hanan-vian** [comment]
Can you please explain yourself, didn't understand.

**Comment by hanan-vian** [comment]
https://github.com/hanan-vian/awesome-pipeline/tree/steppy

**Comment by pditommaso** [comment]
I mean to use the following link instead of the docs one 

https://github.com/minerva-ml/steppy

**Comment by hanan-vian** [comment]
@pditommaso  done

**Comment by pditommaso** [comment]
Cool. Thanks!

**Pull request merged**
