### PR TITLE
Add Nix

### PR DESCRIPTION
**Pull request by davidsoergel**

### CODE REVIEW

**Comment by pditommaso** [comment]
Indeed, this is a very interesting tool. However, even if it can be used to enhance pipelines reproducibility, it is not a pipeline or a workflow management tool. For this reason I'm not keen to include it in this list.

**Comment by davidsoergel** [comment]
Sure it is-- I used it to drive all the computations for my 2010 dissertation, with exactly the goals of all the other tools.  It's not marketed as a workflow tool, but in terms of actual functionality, there's no difference.  That said, if the purpose of the list is to include only things that practicing scientists are likely to actually use, then I agree Nix shouldn't be included, simply because there's no marketing or documentation about using it this way.

**Comment by pditommaso** [comment]
In fact, this is exactly the reason I didn't include either GNU Make in this list.

**Comment by davidsoergel** [comment]
OK, that makes sense, thanks.  Make is indeed perfectly analogous.

**Pull request closed without merging**
