### PR TITLE
Add new category for systems which orchestrates workflow runs by other tools

### PR DESCRIPTION
**Pull request by samuell**
[Arteria](https://arteria-project.github.io/) is a system that does not implement a workflow engine by itself, but which does event-driven workflow initiation of workflows written in other tools.

This seems like it might need a new category.

### CODE REVIEW

**Comment by pditommaso** [comment]
Hi! sorry for the late answer. This looks an interesting project, but not sure we should add a new section for it.

**Comment by samuell** [comment]
@pditommaso No worries! Not sure either. Do you think it would fit among other pipeline systems?

**Comment by samuell** [comment]
Maybe under "Workflow platforms" ?

**Comment by pditommaso** [comment]
Yes, let's put it under Workflow platforms. Thanks!

**Comment by samuell** [comment]
Ok! I'll start a new PR, to avoid double commits.

**Pull request closed without merging**
