### PR TITLE
add omega|ml

### PR DESCRIPTION
**Pull request by miraculixx**
Propose to add omega|ml - Fast, easy machine learning deployment & collaboration for humans (with Python).

Thanks!

### CODE REVIEW

**Comment by pditommaso** [comment]
Would you agree to add it only in the *ETL* section?

**Comment by miraculixx** [comment]
Thanks for asking. Actually omega|ml is more like KNIME Analytics Platform so I would prefer to keep it in the same section, but can remove it from ETL to have it listed only once. Would that work for you?

**Comment by pditommaso** [comment]
I agree!

**Comment by miraculixx** [comment]
thanks! fixed.

**Comment by pditommaso** [comment]
Cool. thanks

**Pull request merged**
