### PR TITLE
Add Lyft's Flyte

### LINKED ISSUE #116: Add Lyft's Flyte
https://eng.lyft.com/introducing-flyte-cloud-native-machine-learning-and-data-processing-platform-fb2bb3046a59

### PR DESCRIPTION
**Pull request by austinkeller**
Resolves #116

### CODE REVIEW

**Comment by austinkeller** [comment]
I could see an argument for this being a platform instead of a pipeline framework.

Also, I used the documentation's description for the summary sentence(s), but it ended up being slightly longer than any of the other summaries. I'm open to suggestions of how to shorten this.

**Comment by pditommaso** [comment]
Sorry for the late and thanks for your contribution. Yes, being a platform it would make sense to move it in the *Platform* section. 

A more concise description would be appreciated. For example (taking from your readme): 

> K8s-native extensible orchestration engine that manages the core machine learning pipelines at Lyft

**Comment by cloneluke** [comment]
@pditommaso Flyte never got merged?

**Comment by cloneluke** [comment]
@pditommaso Flyte never got merged?

**Pull request closed without merging**
