### PR TITLE
Add DVC.org

### PR DESCRIPTION
**Pull request by dmpetrov**

### CODE REVIEW

**Comment by pditommaso** [comment]
Very interesting project. Not sure tho, it should go in the workflow engine category. Maybe in the ETL section ?

**Comment by mroutis** [comment]
Probably on the "Pipeline frameworks & libraries" section, @pditommaso :slightly_smiling_face:

**Comment by mroutis** [comment]
Thanks for the update, @dmpetrov ! :)

**Comment by dmpetrov** [comment]
@pditommaso it is a good point. I think @mroutis is right about `Pipeline frameworks & libraries`. Moved there.

**Comment by pditommaso** [comment]
Sorry for the huge delay. I think this tools deserve its own section. I've put in under *ETL & Data orchestration*. See 8c57e5c. 

Thanks for your contribution.

**Comment by dmpetrov** [comment]
Thank you, @pditommaso

**Pull request closed without merging**
