### PR TITLE
Describe NextflowWorkbench

### PR DESCRIPTION
**Pull request by fac2003**
I've added a link under platforms.

### CODE REVIEW

**Comment by pditommaso** [comment]
OK, I need to merge it manually, thus I'm closing this pull request. Tx!

**Comment by pditommaso** [comment]
Also, I've removed `for beginners and experts` because I'm trying to keep all descriptions in one line. Hope it's not a problem.

**Comment by fac2003** [comment]
Not a problem, but I hope you realize one line means nothing in HTML,
depends on the width of one's screen, so quite arbitrary.

On Fri, Mar 25, 2016 at 3:54 AM Paolo Di Tommaso <notifications@github.com>
wrote:

> Also, I've removed for beginners and experts because I'm trying to keep
> all descriptions in one line. Hope it's not a problem.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/pditommaso/awesome-pipeline/pull/34#issuecomment-201189833>
>
-- 

Fabien Campagne, PhD -- http://campagnelab.org

                                          @FabienCampagne
<https://twitter.com/FabienCampagne>

Assistant Professor, Dept. of Physiology and Biophysics

                         Institute for Computational Biomedicine

Associate Director,   Biomedical Informatics Core,

                      Clinical Translational Science Center

Weill Medical College of Cornell University

phone:  (646)-962-5613  1305 York Avenue

fax:    (646)-962-0383  Box 140

New York, NY 10021

Learn about Data Analysis with MetaR. http://metaR.campagnelab.org
<http://metar.campagnelab.org/>

**Comment by pditommaso** [comment]
Of course, but the reason is mostly to maintain a basic uniformity between all descriptions. Feel free to reopen the pull request if you are not happy with that. 

Cheers, p

**Comment by fac2003** [comment]
It's fine. I would just suggest to clarify the maximum length of
descriptions (e.g., in characters including spaces), so that submitters
know they have to fit in the limit, or the text will be shortened. The
contributing document only says short and simple, but it looks like your
actual criteria are stricter. Thanks. Fabien

On Fri, Mar 25, 2016 at 10:32 AM Paolo Di Tommaso <notifications@github.com>
wrote:

> Of course, but the reason is mostly to maintain a basic uniformity between
> all descriptions. Feel free to reopen the pull request if you are not happy
> with that.
>
> Cheers, p
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/pditommaso/awesome-pipeline/pull/34#issuecomment-201313653>
>
-- 

Fabien Campagne, PhD -- http://campagnelab.org

                                          @FabienCampagne
<https://twitter.com/FabienCampagne>

Assistant Professor, Dept. of Physiology and Biophysics

                         Institute for Computational Biomedicine

Associate Director,   Biomedical Informatics Core,

                      Clinical Translational Science Center

Weill Medical College of Cornell University

phone:  (646)-962-5613  1305 York Avenue

fax:    (646)-962-0383  Box 140

New York, NY 10021

Learn about Data Analysis with MetaR. http://metaR.campagnelab.org
<http://metar.campagnelab.org/>

**Pull request closed without merging**
