### PR TITLE
Add Kiba ETL

### PR DESCRIPTION
**Pull request by thbar**
Thanks for your great list!

Here is an addition with this Ruby gem I'm maintaining & using to write data pipelines.

### CODE REVIEW

**Comment by pditommaso** [comment]
Thanks for your contribution, however this list collect mainly computational workflows tools and platforms. Maybe could we add Kiba under a new *Extract, transform, load (ETL)* section ?

**Comment by thbar** [comment]
@pditommaso sounds perfectly reasonable to me!

**Comment by pditommaso** [comment]
Could you update your PR adding such section between *Literate programming* and *Build tools*?

**Comment by thbar** [comment]
@pditommaso done!

**Comment by pditommaso** [comment]
Nice and welcome!

**Comment by thbar** [comment]
Thanks!

**Pull request merged**
